### ISSUE TITLE
DBusProxy not refreshed after addition of new dbus object 

### ISSUE THREAD

**Issue by hpthai7** [partnering/node-dbus#12] opened 2017-03-01 17:08 UTC
After adding a new dbus object to a father object using the method `DBusObject.addObject(object, relativePath)`, the object itself cannot be found in the DBusProxy.

Client test-case:
```js
const DBusProxy = dbus.DBusProxy

sessionBus.on('ready', proceed)

function proceed() {
    let skyNode = new DBusProxy(Constant.SERVICE_SKYNODE, sessionBus)
    skyNode.on('connected', onConnectedHandler)
    skyNode.on('disconnected', onDisconnectedHandler)
}
function onConnectedHandler() {
    Promise.try( _ => {
        if (!grandObj.site || !grandObj.site.getChildren().length) {
            log.debug(`No existing sites for test. Creating new site ${id} for testing`)
            return grandFace.Create(id, repo)
        } else {
            log.debug(`Found ${grandObj.site.getChildren().length} existing site objects`)
        }
    })
    .then( _ => {
        log.debug(`grandObj = ${inspect(grandObj)}`) // {Object}
        log.debug(`grandObj.site = ${inspect(grandObj.site)}`) // FIXME: undefined
        log.debug(`grandObj.site.getChildren() = ${inspect(grandObj.site.getChildren())}`)
        // TypeError: Cannot read property 'getChildren' of undefined
    })
}
```
Site interface:
```js
Create (site_id, repo) {
    let obj = new DBusObject(Site.newInstance(site_id, repo, this._dockerHandler))
    this.__dbusObject.addObject(obj, 'site/' + site_id)
}
```

**Comment by nschoe** [comment] 2017-03-06 13:11
I'll fix this now (but when you're submitting an issue, make sure to include a portion of code to reproduce the bug (when possible), because your example is not executable as-is (`grandObj` doesn't exist, for instance).

Anyway, I'm on it.

**Comment by nschoe** [comment] 2017-05-22 14:00
Issue closed in branch DBusProxy

**Closed as completed by nschoe** 2017-05-22 14:00 UTC
Labels: bug
